from __future__ import annotations

import json
from pathlib import Path

from .case_bank import build_case_bank
from .models import RunProfile, TestCase

MARKER_START = "<!-- Faulthunter:auto-catalog:start -->"
MARKER_END = "<!-- Faulthunter:auto-catalog:end -->"

DEFAULT_SPEC_RELATIVE = Path("specs/FEATURE_TEST_SPEC.md")

# Stable preamble: hand-edit above the markers; do not remove the marker lines.
_FEATURE_SPEC_PREAMBLE = """# FaultHunter feature test specification

FaultHunter evaluates TradeTalk HTTP surfaces against independent benchmarks. This document
describes the evaluation architecture and lists every `TestCase` (authoritative source: Python
[`case_bank.py`](faulthunter/case_bank.py)).

## Evaluation pattern (agent-architect framing)

- **Workflow**: treat FaultHunter as a **loop** — capture the target response, pull external
  reference data, compare and judge until each case is scored.
- **Target**: TradeTalk via the HTTP adapter (`faulthunter/targets/tradetalk.py`).
- **External toolbox (“MCP” analogy)**:
  - **Yahoo / `yfinance`**: numeric benchmarks and parity fields for supported cases.
  - **Optional browser probe**: Playwright snippet from a public quote URL for supplemental evidence
    (not a full site walkthrough).

## Run profiles

| Profile | Scope |
|---------|--------|
| `smoke` | Core cases; fast feedback. |
| `daily` | Smoke cases plus additional daily coverage. |
| `deep` | Currently identical to `daily` in `build_case_bank` until extended. |

---

"""


def _case_summary_lines(cases: list[TestCase]) -> list[str]:
    lines: list[str] = []
    for c in cases:
        q = json.dumps(c.query, sort_keys=True) if c.query else "{}"
        lines.append(
            f"- **`{c.id}`** — `{c.feature}` · `{c.method} {c.endpoint}` · "
            f"freshness `{c.required_freshness}` · query `{q}`"
        )
    return lines


def render_auto_catalog() -> str:
    """Markdown body placed between MARKER_START and MARKER_END (exclusive of markers)."""
    smoke = build_case_bank(RunProfile.SMOKE)
    daily = build_case_bank(RunProfile.DAILY)
    smoke_ids = {c.id for c in smoke}
    daily_only = [c for c in daily if c.id not in smoke_ids]

    lines: list[str] = [
        "## Auto-generated case catalog",
        "",
        "*Regenerated by `python -m faulthunter.cli --emit-feature-spec` — do not edit by hand.*",
        "",
        "### Profile `smoke`",
        "",
        f"**Count:** {len(smoke)}",
        "",
        *_case_summary_lines(smoke),
        "",
        "### Profile `daily`",
        "",
        f"**Count:** {len(daily)} (includes all smoke cases plus {len(daily_only)} additional).",
        "",
        "#### Daily-only cases (not in smoke)",
        "",
        *(
            (f"- **`{c.id}`** — `{c.feature}`" for c in daily_only)
            if daily_only
            else ("- *(none)*",)
        ),
        "",
        "### Full snapshots (`model_dump`)",
        "",
        "```json",
        json.dumps(
            {
                "smoke": [c.model_dump(mode="json") for c in smoke],
                "daily": [c.model_dump(mode="json") for c in daily],
                "daily_only_ids": [c.id for c in daily_only],
            },
            indent=2,
        ),
        "```",
        "",
        "### Profile `deep`",
        "",
        "Uses the same list as `daily` until `build_case_bank` defines a distinct deep set.",
        "",
    ]
    return "\n".join(lines)


def extract_catalog_region(full_text: str) -> str:
    """Return the markdown between markers; raises if markers are missing or mis-ordered."""
    if MARKER_START not in full_text or MARKER_END not in full_text:
        msg = f"Expected both {MARKER_START!r} and {MARKER_END!r} in the spec file."
        raise ValueError(msg)
    inner = full_text.split(MARKER_START, 1)[1].split(MARKER_END, 1)[0]
    return inner.strip("\n")


def splice_catalog(full_text: str, generated: str) -> str:
    """Replace the region between markers with `generated` (normalized trailing newline)."""
    if MARKER_START not in full_text or MARKER_END not in full_text:
        raise ValueError(
            f"Cannot splice: missing {MARKER_START!r} or {MARKER_END!r}.",
        )
    before, _, rest = full_text.partition(MARKER_START)
    _, _, after = rest.partition(MARKER_END)
    gen = generated.strip("\n") + "\n"
    return before + MARKER_START + "\n" + gen + MARKER_END + after


def default_document_with_catalog(generated: str) -> str:
    """Full file for a first-time write: preamble + markers + catalog."""
    gen = generated.strip("\n") + "\n"
    return (
        _FEATURE_SPEC_PREAMBLE
        + "\n"
        + MARKER_START
        + "\n"
        + gen
        + MARKER_END
        + "\n"
    )


def emit_feature_spec(path: Path) -> None:
    """Write or update the feature spec file at `path` (absolute or cwd-relative)."""
    generated = render_auto_catalog()
    path = path.resolve()
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(default_document_with_catalog(generated), encoding="utf-8")
        return

    text = path.read_text(encoding="utf-8")
    if MARKER_START not in text or MARKER_END not in text:
        raise ValueError(
            f"{path} exists but is missing catalog markers. "
            f"Add {MARKER_START} and {MARKER_END} around the auto-generated block, "
            "or delete the file to recreate from the default template.",
        )
    path.write_text(splice_catalog(text, generated), encoding="utf-8")
